### ISSUE TITLE
How to change the width,Height of video format to 1280*960?

### ISSUE THREAD

**Issue by yingya1992** [TheImagingSource/Linux-tiscamera-Programming-Samples#1]
Hi
  The camera won't start when I change the width,Height of video format to 1280*960,how to fix it?
```
Tis = TIS.TIS("28210384", 1280, 960, 15, True, True)
```

**Comment by srinath-ramachandran** [comment]
Hey @yingya1992 try to use tcam-ctrl -p _serial-number_ to verify the resolution is valid for your camera or trigger is valid (Not sure about the trigger part). Sometimes in trigger mode, high resolutions depend on an increased delay in pulses if you're talking about triggering externally. Try using 640x480 first and then work on the trigger side to delay the pulses further for higher resolution.

**Comment by davidsean** [comment]
If the 1280x960 isn't supported and you MUST have it, you can try to add a Gst pipeline element to rescale the video.
For example, you could add this in the TIS class after the `p = 'tcambin...`
`p +=  "! videoscale ! video/x-raw, width=1280, height=960 ! videoconvert "`

Note that this only rescales the video and may not be what you want. In all cases, @sxr3455 is correct and you should always choose a format (both resolution **and framerate**) supported  by the camera first.
