### ISSUE TITLE
Hoe to adjust the brigtness in the image

### ISSUE THREAD

**Issue by f2013619** [TheImagingSource/Linux-tiscamera-Programming-Samples#10]
Hi, 
I was trying to use the program of Saving an image using openCv in C++ and the output is yellowish colourewd image. what can I do to improve it and how to set the brightness at a fixed vale in the code.

**Comment by TIS-Stefan** [comment]
Sorry for the extremely long delay of my answer.
Which camera model do you use?
However, it looks for a white balance issue, in case, it is a properties issue. 
In case you use a module camera without housing, you may need to remove the brown protection foil from the sensor.
