### ISSUE TITLE
How to get GstTcamMeta fields in python?

### ISSUE THREAD

**Issue by tahasadr** [TheImagingSource/Linux-tiscamera-Programming-Samples#12]
Hi there 
we want to check if any frame has been lost or not, during our capture time.
i came to find GstTcamMeta provide camera frame number, but i cannot find a way to use it in python?
Model: DFM 37UX273
tiscamera 0.14.0

**Comment by tahasadr** [comment]
> Hi there
> we want to check if any frame has been lost or not, during our capture time.
> i came to find GstTcamMeta provide camera frame number, but i cannot find a way to use it in python?
> Model: DFM 37UX273
> tiscamera 0.14.0
any help would be appreciated?!
@TIS-Stefan @TIS-Alexander @TIS-Arne @TIS-Christopher @TIS-Edgar @TIS-Michael

**Comment by TIS-Stefan** [comment]
I am very sorry, but in Python you do not have an access to the meta data currently. Otherwise, we had provided an example, like we did in C.
Maybe it comes in the next version of tiscamera, but currently there is no deadline for doing that.

**Comment by hidon** [comment]
> I am very sorry, but in Python you do not have an access to the meta data currently. Otherwise, we had provided an example, like we did in C. Maybe it comes in the next version of tiscamera, but currently there is no deadline for doing that.

Dear @TIS-Stefan @TIS-Alexander @TIS-Arne @TIS-Christopher @TIS-Edgar @TIS-Michael 
I want to get metedata(camera_time_ns and cap_time_ns) but any opencv project  not include this meatdata varible. I need how can get it? thanks for reply.

**Comment by TIS-Stefan** [comment]
I am afraid my last answer was not completely correct.

You can get the data with our tiscamera 1.0 Gstreamer Modules in C++ and in Python. The "examples" directory contains matching examples. After "git clone" you run "git checkout development" and build tiscamera. Then you will have the samples.  

The cv::Videocapture class can not retrieve this meta data.

Stefan

**Comment by hidon** [comment]
Dear Stefan,
I copied some source code to  github project "Linux-tiscamera-Programming-Samples/OpenCV-Gstreamer-GetImage/main.cpp" that related metadata of camera from 10-metadata.c file. compiled it succesfully jetson xaiver nx.
but I am not sure this code working correctly. Actually I care about old and new camera_time_ns difference as latency. at this stage latency meausurement is reasonable or not? 


#include "gstmetatcamstatistics.h"   // Metada added for camera_time_ns 23MAY2022
.
.
.
 // Metada added for camera_time_ns 23MAY2022
    GstSample* sample = NULL;
    guint64 camera_time_ns = 0;
    guint64 oldcamera_time_ns = 0;
    guint64 frame_latency =0;
    while( !CustomData.newImage )
    {
        usleep(100);
 	// Metada added for camera_time_ns  23MAY2022
	GstBuffer* buffer = gst_sample_get_buffer(sample);
	GstMeta* meta = gst_buffer_get_meta(buffer, g_type_from_name("TcamStatisticsMetaApi"));
	GstStructure* struc = ((TcamStatisticsMeta*)meta)->structure;
        gst_structure_get_uint64(struc, "camera_time_ns", &camera_time_ns);
	frame_latency=camera_time_ns-oldcamera_time_ns;
	oldcamera_time_ns=camera_time_ns;
        printf("frame_latency: %ul\n", frame_latency);
	// Metada added for camera_time_ns  23MAY2022
	
    }

best regards.

**Comment by TIS-Stefan** [comment]
Hi

If all works as expected, then the "frame_latency" is the time between two frames, which should be 1/frame_rate. 
I would guess, the 100µs you pass to usleep could be somewhat short. 
If CustomData.newImage is set to true once, your loop will not terminate, because you do not set it to false in your loop. 
I wonder about the complete context, because your code does not make sense to me.  I mean, there is a non terminating while loop and you get a sample from somewhere., which may is null or not. 

Stefan

**Comment by hidon** [comment]
Hi,
you have better example to get each frame value of camera_time_ns?  Now noticed that new_frame_cb callback function is more suitable than "while" for camera_times_ns. 

Halil.

**Comment by TIS-Stefan** [comment]
Hello Halil

I can point to the sample in the tiscamera/examples/c directory only. 
The callback is the correct position in order to get the GstSample. 

Stefan

**Comment by hidon** [comment]
why do not update github project OpenCV-Gstreamer-GetImage project. if I have tiscamera . I want to do that. but the camera searching for my projects is going on. thanks Stefan.

**Comment by TIS-Stefan** [comment]
> why do not update github project OpenCV-Gstreamer-GetImage project. if I have tiscamera . I want to do that. but the camera searching for my projects is going on. thanks Stefan.

I must admit, I do not understand, what you mean.  What is the "github project OpenCV-Gstreamer-GetImage project"?

Thank you in advance
Stefan

**Comment by hidon** [comment]
can be added metadata this project.

**Comment by TIS-Stefan** [comment]
"can be added metadata this project." If this is a question, yes. You can add the meta data code to this project. 

If you speak about the project at 
https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/master/OpenCV-Gstreamer-GetImage/main.cpp, then there is a callback. 

There is also a struct, 
```
// Create a custom data structure to be passed to the callback function. 
typedef struct
{
    int ImageCounter;
    bool SaveNextImage;
    bool newImage;
   	cv::Mat frame; 
} CUSTOMDATA;
```
Which is passed to the callback. You can add a member to this struct for the frame time stamp
```
// Create a custom data structure to be passed to the callback function. 
typedef struct
{
    int ImageCounter;
    bool SaveNextImage;
    bool newImage;
    cv::Mat frame;
   guint64 camera_time_ns; 
   guint64 oldcamera_time_ns;
   guint64 frame_latency;
} CUSTOMDATA;
```

In the callback `GstFlowReturn new_frame_cb(GstAppSink *appsink, gpointer data)` you add the code for the meta data from the meta data example:
```
////////////////////////////////////////////////////////////////////
// Callback called for new images by the internal appsink
GstFlowReturn new_frame_cb(GstAppSink *appsink, gpointer data)
{
    int width, height ;
    const GstStructure *str;

    // Cast gpointer to CUSTOMDATA*
    CUSTOMDATA *pCustomData = (CUSTOMDATA*)data;
    if( !pCustomData->SaveNextImage)
        return GST_FLOW_OK;
    pCustomData->SaveNextImage = false;

    pCustomData->ImageCounter++;

    // The following lines demonstrate, how to access the image
    // data in the GstSample.
    GstSample *sample = gst_app_sink_pull_sample(appsink);

    GstBuffer *buffer = gst_sample_get_buffer(sample);

	GstMeta* meta = gst_buffer_get_meta(buffer, g_type_from_name("TcamStatisticsMetaApi"));
	GstStructure* struc = ((TcamStatisticsMeta*)meta)->structure;
	gst_structure_get_uint64(struc, "camera_time_ns", &(pCustomData->camera_time_ns));
	pCustomData->frame_latency= pCustomData->camera_time_ns-pCustomData->oldcamera_time_ns;
	pCustomData->oldcamera_time_ns=pCustomData->camera_time_ns;

    GstMapInfo info;

    gst_buffer_map(buffer, &info, GST_MAP_READ);
    
    if (info.data != NULL) 
    {
        // info.data contains the image data as blob of unsigned char 

        GstCaps *caps = gst_sample_get_caps(sample);
        // Get a string containg the pixel format, width and height of the image        
        str = gst_caps_get_structure (caps, 0);    

        // Now query the width and height of the image
        gst_structure_get_int (str, "width", &width);
        gst_structure_get_int (str, "height", &height);

        // Get the pixelformat of the Buffer
        std::string format = gst_structure_get_string (str, "format");

        if( format == "BGRx")  
        {
            // Create a cv::Mat, copy image data into that and save the image.
            pCustomData->frame.create(height,width,CV_8UC(4));
            memcpy( pCustomData->frame.data, info.data, width*height*4);        
        }
        else if( format == "BGR" )
        {
            pCustomData->frame.create(height,width,CV_8UC(3));
            memcpy( pCustomData->frame.data, info.data, width*height*3);        
        }
        else if( format == "GRAY8" )
        {
            pCustomData->frame.create(height,width,CV_8UC(1));
            memcpy( pCustomData->frame.data, info.data, width*height);        
        }
        else if( format == "GRAY16_LE" )
        {
            pCustomData->frame.create(height,width,CV_16UC(1));
            memcpy( pCustomData->frame.data, info.data, width*height*2);        
        }
        else if( format == "RGBx64" )
        {
            pCustomData->frame.create(height,width,CV_16UC(4));
            memcpy( pCustomData->frame.data, info.data, width*height*8);        
        }
        else 
        {
            printf("Unknown format %s\n",format.c_str());
        }
        
        pCustomData->newImage = true;
    }
    
    // Calling Unref is important!
    gst_buffer_unmap (buffer, &info);
    gst_sample_unref(sample);

    // Set our flag of new image to true, so our main thread knows about a new image.
    return GST_FLOW_OK;
}

```
I did not test this, the code was simply copied. You may try this.

Stefan

**Comment by hidon** [comment]
Thanks Stefan,

compiled it succes. But I can not try it with tis camera. 
I want to select tis camera for my projects. see who I should for suitable camera selections? please I want to connect technical person not purchasing persons.

Halil.

**Comment by TIS-Stefan** [comment]
Hello Halil

You may contact us at https://www.theimagingsource.com/support/contact/

Stefan

**Comment by TIS-Stefan** [comment]
tiscamera 1.0 supports meta data in Python
