### ISSUE TITLE
What Python Versions are the Python Examples Samples for?

### ISSUE THREAD

**Issue by gusrbgks** [TheImagingSource/Linux-tiscamera-Programming-Samples#13]
I'm trying to run the Python Example code.
But when I run it with python2.7 I get a SyntaxError.
When I run it in Python3, I get the following error:

![Screenshot from 2021-08-26 12-21-39](https://user-images.githubusercontent.com/76414191/130895447-f6b15c03-e797-4604-ae54-b66b6deeb66a.png)

Can you tell me why?

**Comment by TIS-Edgar** [comment]
It seems there is a mistake in TIS.py.

Can you try to add `Gst.init([])` before the line `DeviceInfo = namedtuple("DeviceInfo", "status name identifier connection_type")`.
in the file python-common/TIS.py.

**Comment by gusrbgks** [comment]
thank you.
This issue has been resolved.
