### ISSUE TITLE
Hang in self.pipeline.set_state(Gst.State.PLAYING) in Start_pipeline()

### ISSUE THREAD

**Issue by tzuchen0814** [TheImagingSource/Linux-tiscamera-Programming-Samples#16]
Hi, 

I've compiled and installed the tiscamera SDK on my system and everything seems to be working fine.

I can take a picture, but sometimes it hang in self.pipeline.set_state(Gst.State.PLAYING) in Start_pipeline() or in self.pipeline.set_state(Gst.State.NULL) in Stop_pipeline().

env:
gi.require_version("Gst", "1.0")
gi.require_version("Tcam", "0.1")
Raspberry Pi Debian GNU/Linux 10 (buster) & Python 3.6.9

What may be the cause of this?

**Comment by TIS-Stefan** [comment]
Should be fixed in tiscamera 1.0
