### ISSUE TITLE
gi.repository error while running .py files in Window Command Prompt

### ISSUE THREAD

**Issue by iitdpooja** [TheImagingSource/Linux-tiscamera-Programming-Samples#17]
Dear Stefan,

I want to run python scripts in windows with 2 TIS cameras. But I am not able to install gi files using pip install. 

'File "C:\Users\shiva\OneDrive\Documents\Pooja\Project_GAIT\Scripts_TIS_Cameras\Python-Multiple-Cameras-Triggered\multi-camera-simple.py", line 9, in <module>
    import TIS
  File "C:\Users\shiva\OneDrive\Documents\Pooja\Project_GAIT\Scripts_TIS_Cameras\Python-Multiple-Cameras-Triggered\TIS.py", line 4, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

Can you please suggest something for this. It will be a great help.

**Comment by nilvana-taka** [comment]
`gi.repository` module is called PyGObject and is for Gtk+3 and is not yet available for Windows.

If you are working on the Ubuntu environment, maybe you can try the following commands:
```
sudo apt install libcairo2-dev libxt-dev libgirepository1.0-dev
pip install pycairo PyGObject
```
