### ISSUE TITLE
I use the 'snap an image and convert to opencv' sample code, but why does it have two video images?

### ISSUE THREAD

**Issue by yi232** [TheImagingSource/Linux-tiscamera-Programming-Samples#19]
Hello! I use the 'snap an image and convert to opencv' example code, but it will appear two identical video images, one window is called 'window' and the other window is called 'Python'. When I close the 'Python' window, the 'window' screen will not move, and I find that I can only control the 'window'. And I only created a 'window' window. I don't know where this' Python 'window comes from. I don't want the' Python 'window to be displayed, okay? What should I do? Thank you

**Comment by nilvana-taka** [comment]
@yi232 just set `showvideo` field to False in your TIS.py class. https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/master/python/python-common/TIS.py#L347
