### ISSUE TITLE
Partial image buffer memory copy in Python

### ISSUE THREAD

**Issue by copterspace** [TheImagingSource/Linux-tiscamera-Programming-Samples#20]
Dear colleagues, I test https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/master/python-common/TIS.py  with DMM 37UX252-ML on Raspberry PI 4 with Python3.7

Camera gives 2048x1536 8-bit frames at ~120 FPS via gstreamer

But I have trouble with line 175: https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/da293f1841444b7697394c899aaa4f03343125ea/python-common/TIS.py#L175 

it takes about 0.02 seconds to perform 3Mpix frame memory copy `data = info.data` он RPI 4, so framerate drops down from 120 to ~50 fps because of this.

In my application I only need some ROI from the frame center, so partial copy `data = info.data[20:40]` could solve the task.
But `data = info.data[20:40]` takes the same ~0.02 sec as `data = info.data` - seems Python copies the whole buffer, despite I need only part of it.

How could I properly copy only part of frame buffer to store in memory, in manner of `data = info.data[20:40]` in Python3 ?

**Comment by TIS-Stefan** [comment]
I am sorry for the delay of my answer, I got no notifications from github about issue changes. 

The PI4 USB connection is fast enough, but as soon as you make something with the image data, the PI4 is far too week for this frame rate. 

Is the issue still open?

Stefan

**Comment by copterspace** [comment]
I moved to Jetson Nano, it is faster and works OK. RPI4 is too slow for this type of camera.
