### ISSUE TITLE
Needs porting for tiscamera 1.0

### ISSUE THREAD

**Issue by ximion** [TheImagingSource/Linux-tiscamera-Programming-Samples#21]
Hi!
The xamples in this repository currently do not compile with the new TISCamera 1.0 release. It would be nice to get them ported to the latest API, also as reference as to how this porting should be done in other projects.
Thank you! :-)

**Comment by MaxFhG** [comment]
Hello,
it would also be good for me to have the documentation for ROS in the current TISCamera 1.0 release. I noticed that the ROS folder was actually deleted today. Is there a time-schedule when the new version for ROS (TISCamera 1.0) will be available?

Thank You for the current update for TISCamera 1.0

**Comment by TIS-Stefan** [comment]
I am sorry for the delay of my answer, I got no notications from github about issue changes. 

We removed the ROS sample, because there is a GSCAM plugin for ROS, which should be used. 

Stefan

**Comment by ximion** [comment]
It would be nice to have https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/tree/master/cpp/QT5%20Device%20Selection%20and%20Property%20Dialogs, the "Qt5 Device Selection and Property Dialogs" example ported as well, as it is very complete in showing what the cameras can do.
Right now when I try to compile it, it complains about the missing "tcamprop.h" header.

**Comment by TIS-Stefan** [comment]
I agree with you. However, the tcam-capture source code implements a property dialog too. Could that be helpful?

Stefan

**Comment by ximion** [comment]
I wanted to write that that code was in Python, but since tiscamera 1.0 it's actually C++ too! Really nice!
I will have a look, this may actually save me a lot of work - thank you for the hint!

**Comment by ximion** [comment]
By the way, the availability of source code, and also great support on Linux, elevates these cameras above everything else - compared to what we used before, it's a pleasure to work with the devices. So, thank you for putting in all the work and making sources available!

**Comment by TIS-Stefan** [comment]
Thank you for the compliment!

Stefan

**Comment by TIS-Stefan** [comment]
BTW:
The following is an MDI project with extra h and cpp files for the dialogs. The device selection dialog also allows to select an ROI if supported by the camera. The properties dialog is also somewhat different from tcam-capture: view-level, checkbox for property descriptions.

I hope, it compiles....

[tis-capture.zip](https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/files/10805334/tis-capture.zip)

Stefan

**Comment by ximion** [comment]
Thank you! - It didn't build at first, but was easy to make work. Now it runs, but likes to crash occasionally (but that can be worked out) Very nice!
