### ISSUE TITLE
Pixel depth on RGBx64 image with DFM37UX178

### ISSUE THREAD

**Issue by manuInWound** [TheImagingSource/Linux-tiscamera-Programming-Samples#26]
Hi, I am working last weeks to use my DFM37UX178 working  with external trigger and for capturing pictures with the highest pixel depth the camera is able to provide. My OS is Ubuntu 20.04. TIS support help me to solve some trigger bugs on python and now I am facing some problems to have the real RGBx64 image on c++ (4 channels 16 bits). My code is saving a picture in .TIFF format with 12.6 MB size but unfortunately its still a 8bit per pixel image. I am testing with c++ because in python the RGBx64 does not worked for me.

`//////////////////////////////////////////////////////////////////
/*
Tcam Software Trigger
This sample shows, how to trigger the camera by software and use a callback for image handling.

Prerequisits
It uses the the examples/cpp/common/tcamcamera.cpp and .h files of the *tiscamera* repository as wrapper around the
GStreamer code and property handling. Adapt the CMakeList.txt accordingly.
*/
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <iostream>

#include <unistd.h>

#include <gst/gst.h>
#include <gst/app/gstappsink.h>

#include "opencv2/opencv.hpp"

// Create a custom data structure to be passed to the callback function. 
typedef struct
{
    int ImageCounter;
    bool SaveNextImage;
    bool newImage;
   	cv::Mat frame; 
} CUSTOMDATA;

////////////////////////////////////////////////////////////////////
// Callback called for new images by the internal appsink
GstFlowReturn new_frame_cb(GstAppSink *appsink, gpointer data)
{
    int width, height ;
    const GstStructure *str;

    // Cast gpointer to CUSTOMDATA*
    CUSTOMDATA *pCustomData = (CUSTOMDATA*)data;
    if( !pCustomData->SaveNextImage)
        return GST_FLOW_OK;
    pCustomData->SaveNextImage = false;

    pCustomData->ImageCounter++;

    // The following lines demonstrate, how to acces the image
    // data in the GstSample.
    GstSample *sample = gst_app_sink_pull_sample(appsink);

    GstBuffer *buffer = gst_sample_get_buffer(sample);

    GstMapInfo info;

    gst_buffer_map(buffer, &info, GST_MAP_READ);
    
    if (info.data != NULL) 
    {
        // info.data contains the image data as blob of unsigned char 

        GstCaps *caps = gst_sample_get_caps(sample);
        // Get a string containg the pixel format, width and height of the image        
        str = gst_caps_get_structure (caps, 0);    

        // Now query the width and height of the image
        gst_structure_get_int (str, "width", &width);
        gst_structure_get_int (str, "height", &height);

        // Get the pixelformat of the Buffer
        std::string format = gst_structure_get_string (str, "format");

        if( format == "BGRx")  
        {
            // Create a cv::Mat, copy image data into that and save the image.
            pCustomData->frame.create(height,width,CV_8UC(4));
            memcpy( pCustomData->frame.data, info.data, width*height*4);        
        }
        else if( format == "BGR" )
        {
            pCustomData->frame.create(height,width,CV_8UC(3));
            memcpy( pCustomData->frame.data, info.data, width*height*3);        
        }
        else if( format == "GRAY8" )
        {
            pCustomData->frame.create(height,width,CV_8UC(1));
            memcpy( pCustomData->frame.data, info.data, width*height);        
        }
        else if( format == "GRAY16_LE" )
        {
            pCustomData->frame.create(height,width,CV_16UC(1));
            memcpy( pCustomData->frame.data, info.data, width*height*2);        
        }
        else if( format == "RGBx64" )
        {
            pCustomData->frame.create(height,width,CV_16UC(4));
            memcpy( pCustomData->frame.data, info.data, width*height*8);        
        }
        else 
        {
            printf("Unknown format %s\n",format.c_str());
        }
         
     
        char ImageFileName[256];
        sprintf(ImageFileName,"image%05d.tiff", pCustomData->ImageCounter);
        cv::imwrite(ImageFileName,pCustomData->frame);
        
        pCustomData->newImage = true;
    }
    
    // Calling Unref is important!
    gst_buffer_unmap (buffer, &info);
    gst_sample_unref(sample);

    // Set our flag of new image to true, so our main thread knows about a new image.
    return GST_FLOW_OK;
}

/////////////////////////////////////////////////////////////////////
// State change call with some more error handling.
bool WaitForChangeState(GstElement *pipeline, GstState newState)
{
	char ErrorText[1024];
	ErrorText[0] ='\0';
	
	GstStateChangeReturn Result = gst_element_set_state( pipeline, newState);
	if( Result == GST_STATE_CHANGE_FAILURE )
	{
		printf("FAILURE set state() () change to state %d failed\n", newState);
		return false;
	}

	Result = gst_element_get_state( pipeline, NULL, NULL, 4000000000ll);

	if( Result == GST_STATE_CHANGE_FAILURE )
	{
		printf("FAILURE WaitForChangeState() change to state %d failed\n", newState);
		return false;
	}

	if( Result == GST_STATE_CHANGE_ASYNC )
	{
		printf("ASYNC WaitForChangeState() change to state %d failed\n", newState);
		return false;
	}
	return true;
}                   

///////////////////////////////////////////////////////////////////////////////////////////////////
// Create the pipeline and add the sink callback
// cbdata is callback user data.
GstElement* CreatePipeline( std::string PipeLineString, void* cbdata)
{
    printf("%s\n",PipeLineString.c_str());

    GError *error = NULL;         
 	GstElement *pipeline = gst_parse_launch (PipeLineString.c_str(), &error);            

    if (error)
	{
		printf( "Error building Camera pipeline: %s\n", error->message);
		return NULL;
	}        

	GstAppSink *appsink = (GstAppSink*)gst_bin_get_by_name(GST_BIN(pipeline), "sink");
	if( appsink != NULL )
	{
		gst_app_sink_set_max_buffers(appsink, 5);
		gst_app_sink_set_drop(appsink, true); 
		
		GstAppSinkCallbacks callbacks;
		callbacks.eos = NULL;
		callbacks.new_preroll = NULL;
		callbacks.new_sample = new_frame_cb;
		
		gst_app_sink_set_callbacks( appsink, &callbacks, (gpointer) cbdata,NULL);
		
		gst_object_unref(appsink);
	}
	else
    {
		printf("No appsink found. Forgot \" appsink name=sink\"?\n");
        return NULL;
    }

    return pipeline;
}

///////////////////////////////////////////////////////////////////////////////////////////////////
int main(int argc, char **argv)
{
    gst_init(&argc, &argv);
    // Declare custom data structure for the callback
    CUSTOMDATA CustomData;

    CustomData.ImageCounter = 0;
    CustomData.SaveNextImage = false;
    CustomData.newImage = false;

    std::string p = "tcambin name=source device-caps='video/x-raw,format=RGBx64,width=1920,height=1080,framerate=7/1' ! videoconvert ! appsink sync=false name=sink";

    auto pipeline = CreatePipeline( p , &CustomData );
    if( pipeline == NULL)
        return 1;

    if( !WaitForChangeState(pipeline, GST_STATE_PLAYING))
        return 1;

    // Get the next image
    CustomData.newImage = false;
    CustomData.SaveNextImage = true;
    while( !CustomData.newImage )
    {
        usleep(100);
    }

    if( CustomData.newImage)
    {
        // Check the type of OpenCV mat:
        long type = CustomData.frame.type();
        std::string r; 
        uchar depth = type & CV_MAT_DEPTH_MASK;
        uchar chans = 1 + (type >> CV_CN_SHIFT);

        switch ( depth ) {
            case CV_8U:  r = "8U"; break;
            case CV_8S:  r = "8S"; break;
            case CV_16U: r = "16U"; break;
            case CV_16S: r = "16S"; break;
            case CV_32S: r = "32S"; break;
            case CV_32F: r = "32F"; break;
            case CV_64F: r = "64F"; break;
            default:     r = "User"; break;
        }

        r += "C";
        r += (chans+'0');
        
        cv::FileStorage fs("file.yml", cv::FileStorage::WRITE);
        fs << "data" << CustomData.frame;
        
    }
    
    // Simple implementation of "getch()"
    printf("Press Enter to end the program");
    char dummyvalue[10];
    scanf("%c",dummyvalue);
    
    WaitForChangeState(pipeline, GST_STATE_NULL);

    return 0;
}`

**Comment by manuInWound** [comment]
I am trying also with other pipeline but not matter what I put in the format every time the code enter into the RGBx configurations instead of RGBx64

`std::string p = "tcambin name=source device-caps='video/x-bayer,format=GRAY16_LE,width=640,height=480,framerate=5/1' ! videoconvert ! appsink sync=false name=sink";`


I also "forced" the code to configure the pCusomData as RGBx64 and its is able to save data with the 16bit pixel depth but the image is wrong
```

pCustomData->frame.create(height,width,CV_16UC(4));
        memcpy( pCustomData->frame.data, info.data, width*height*8);  
        char ImageFileName[256];
        sprintf(ImageFileName,"image%05d.tiff", pCustomData->ImageCounter);
        cv::imwrite(ImageFileName,pCustomData->frame);
        
        pCustomData->newImage = true;
```


This is the link to see the image https://drive.google.com/file/d/1BcCDmVY0HJszHtQ-bejmSmzpNv3WO7lN/view?usp=share_link

**Comment by TIS-Stefan** [comment]
Hello

I found the solution. But first of all, please make
```
GstAppSinkCallbacks callbacks;
```
a global structure, otherwise you can get an access violation.

The pipeline must be changed to
```
   std::string p = "tcambin  name=source  device-caps=video/x-bayer,format=rggb16 ! video/x-raw,format=RGBx64,width=1920,height=1080,framerate=7/1 ! appsink sync=false name=sink";
```
It is somehow written in the tiscamera documentation that rggb16 is not automatically selected. Therefore, the format must be set in the device caps. I also suppose, the videoconvert makes strange things, so you got rgb only in the appsink.

I hope, that helps. 

I will update the sample regarding the GstAppSinkCallbacks by this week. 

Stefan

**Comment by manuInWound** [comment]
Thank you very much!
