### ISSUE TITLE
qt5-dialogs make error

### ISSUE THREAD

**Issue by qqqtankqqq** [TheImagingSource/Linux-tiscamera-Programming-Samples#29]
I tried to make qt5-dialogs project ,  but I got  a lot of  undefined reference error were as follows:

```
home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cdeviceselectiondlg.cpp:88: undefined reference to `tcam_prop_get_device_serials'
/usr/bin/ld: /home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cdeviceselectiondlg.cpp:95: undefined reference to `tcam_prop_get_device_info'
/usr/bin/ld: CMakeFiles/qt5-dialogs.dir/cpropertiesdialog.cpp.o: in function `CPropertiesDialog::SetCamera(_TcamProp*)':
/home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cpropertiesdialog.cpp:153: undefined reference to `tcam_prop_get_tcam_property_names'
/usr/bin/ld: CMakeFiles/qt5-dialogs.dir/cpropertiesdialog.cpp.o: in function `PropVal::QueryProperty(_TcamProp*, char const*)':
/home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cpropertiesdialog.cpp:273: undefined reference to `tcam_prop_get_tcam_property'
/usr/bin/ld: CMakeFiles/qt5-dialogs.dir/cpropertiesdialog.cpp.o: in function `CPropertyCtrl_int::set_property(char const*, int)':
/home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cpropertiesdialog.cpp:424: undefined reference to `tcam_prop_get_tcam_property_type'
/usr/bin/ld: /home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cpropertiesdialog.cpp:447: undefined reference to `tcam_prop_set_tcam_property'
/usr/bin/ld: CMakeFiles/qt5-dialogs.dir/cpropertiesdialog.cpp.o: in function `CPropertyCtrl_double::set_property(char const*, double)':
/home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cpropertiesdialog.cpp:582: undefined reference to `tcam_prop_get_tcam_property_type'
/usr/bin/ld: /home/gis/shawn/Linux-tiscamera-Programming-Samples/cpp/QT5 Device Selection and Property Dialogs/qt5-camera-dialogs/cpropertiesdialog.cpp:590: undefined reference to `tcam_prop_set_tcam_property'
...
```
how should I solve it ?

**Comment by Priv-Stefan** [comment]
Hello

The sample is written for tiscamera version 0.14. You use version 1.1, thus it wont compile anymore.
I am working on a new sample, but I have not enough time for that currently.

Stefan

**Comment by qqqtankqqq** [comment]
if I need to port property dialog  code, I must use  `TheImagingSource

/tiscamera/tools/tcam-capture` code?
 
 I found you uploaded the `tis-capture.zip` from another issue. but i got error about QGridLayout/QVBoxLayout.

**Comment by TIS-Stefan** [comment]
Hello

Yesterday I had no access to my computer, because there was a holiday in Germany.

[tisdialog.zip](https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/files/11515436/tisdialog.zip)
This is the latest C++ project I work on. It has the dialogs adapted to tiscamera 1.1 
The camera code is completely in the "tcamcamera" subdirectory. 
The main window is designed using the QT Creator. 

I hope, this helps.

Stefan

(I am working on a project wizard, so this project is used as template)

**Comment by qqqtankqqq** [comment]
Hi , Stefen  thanks for builing tisdialog.
I got some little porblem about `gst_video_convert_sample.`
```
/home/gis/shawn/tisdialog/tcamcamera/src/cgrabber.cpp:465:32: error: ‘gst_video_convert_sample’ was not declared in this scope
  465 |   GstSample *convertedSample = gst_video_convert_sample(sample,capsTo,GST_SECOND,&err);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~
```
 I could find  gstream-1.0-video lib,but my include libs path is `/usr/include/gstreamer-1.0/gst/video/`  not `/usr/include/gstreamer-1.0/ ` so I change  include_directories  is still not working.
what's your gstream version?
```
# cmake .. 
--   Found gstreamer-1.0, version 1.16.3
--   Found glib-2.0, version 2.64.6
--   Found gstreamer-base-1.0, version 1.16.3
--   Found gstreamer-app-1.0, version 1.16.3
--   Found gstreamer-video-1.0, version 1.16.3
--   Found gobject-introspection-1.0, version 1.64.1
--   Found gstreamer-plugins-base-1.0, version 1.16.3

GSTREAMER_INCLUDE_DIRS :/usr/include/gstreamer-1.0/  usr/include/gobject-introspection-1.0/  usr/include/gstreamer-1.0/usr/include/glib-2.0/usr/lib/x86_64-linux-gnu/glib-2.0/include/app/
```

**Comment by qqqtankqqq** [comment]
Sorry . i fixed the problem when i found gst_video_convert_sample in  `/usr/include/gstreamer-1.0/gst/video/video.h` .
I added `#include <gst/video/video.h>`  ,so i can open camera and modify property now.

Thanks.

**Comment by TIS-Stefan** [comment]
Hello

Good to know, that I miss a header there. I also was surprised, when I found this gst_video_convert_sample() function in a sample in the internet.
Hopefully the dialogs show up now. 
Stefan

**Comment by TIS-Stefan** [comment]
Hello

I added this #include <gst/video/video.h> in the grabber.cpp, even if the code compiled and linked without that on my computer.

Stefan
