### ISSUE TITLE
software trigger in cpp

### ISSUE THREAD

**Issue by Bardia-Khodadadeh** [TheImagingSource/Linux-tiscamera-Programming-Samples#30]
Hi there
i want cpp code with similar functionality to this c# code below
`        private void IC_SoftWareTrigger()
        {
            TIS.Imaging.VCDButtonProperty SoftTrigger = (TIS.Imaging.VCDButtonProperty)icImagingControl1.VCDPropertyItems.FindInterface(TIS.Imaging.VCDIDs.VCDID_TriggerMode + ":{FDB4003C-552C-4FAA-B87B-42E888D54147}:" + TIS.Imaging.VCDIDs.VCDInterface_Button);
            if (SoftTrigger != null)
            {
                SoftTrigger.Push();
            }
        }
`

**Comment by TIS-Stefan** [comment]
Hi
Please look at https://github.com/TheImagingSource/tiscamera/blob/master/examples/c/06-softwaretrigger.c
I hope, this helps.
