### ISSUE TITLE
CPP examples not working

### ISSUE THREAD

**Issue by bartonp2** [TheImagingSource/Linux-tiscamera-Programming-Samples#39]
I have been trying to run the simple example as well as the 'Save an Image using OpenCV'. While the program compile without errors I get following runtime error:

```
Tcam OpenCV Image Sample
Found serial number "51120118-v4l2".
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not link elements of display pipeline
Aborted (core dumped)
```

Upon commenting out the display line in the example as is suggested in the code, I unfortunately get another error:

`FAILURE set state() () change to state 4 failed`

I have no problem running tcam-capture or gstreamer pipelines directly in the terminal. Only the cpp examples are causing issues.

Am I missing something?

**Comment by TIS-Stefan** [comment]
Hello
I would guess, the camera you use does not support the width, height and frame rate specified. However, I would expect 640x480@30 fps is supported by your DFK 23UX249.  It is the data in this line:

cam.set_capture_format("BGRx", FrameSize{640,480}, FrameRate{30,1});

Please run

tcam-ctrl -c cam.set_capture_format("BGRx", FrameSize{640,480}, FrameRate{30,1});

In order, whether the size and frame rate settings are supported. 

Another point could be, that bayer2rgb is missing, so you may install the tcam-dutils from https://www.theimagingsource.com/en-de/support/download/ under "GStreamer-Plugins"

Stefan

**Comment by bartonp2** [comment]
The line you recommend running did not work. However, I simply ran tcam-ctrl -c to check which caps where supported:

```
tcam-ctrl -c 51120118                                                                        
Available gstreamer-1.0 caps:
video/x-raw,format=GRAY8,width=1280,height=720,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-raw,format=GRAY8,width=1920,height=1080,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-raw,format=GRAY8,width=1920,height=1200,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-bayer,format=gbrg,width=1280,height=720,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-bayer,format=gbrg,width=1920,height=1080,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-bayer,format=gbrg,width=1920,height=1200,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-raw,format=GRAY16_LE,width=1280,height=720,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-raw,format=GRAY16_LE,width=1920,height=1080,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-raw,format=GRAY16_LE,width=1920,height=1200,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-bayer,format=gbrg16,width=1280,height=720,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-bayer,format=gbrg16,width=1920,height=1080,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1};
video/x-bayer,format=gbrg16,width=1920,height=1200,framerate={1/1,5/1,10/1,15/1,20/1,25/1,30/1}
```

When testing the example with "GRAY8" and 1920x1200@30fps the sample worked and it captured an image. With "gbrg" it doesn't seem to work however. tcamdutils is definitely installed:

```
tcam-ctrl --packages
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: va_openDriver() returns -1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: va_openDriver() returns -1
tiscamera: 1.1.0.4139
tiscamera-tcamproperty: Provided by tiscamera
tcamdutils: 1.0.0.560
tcampimipisrc is not installed.
tcamtegrasrc is not installed.
tcamdutils-cuda is not installed.
theimagingsource-drivers is not installed.
ic_barcode is not installed.
```

Further, the result of the "GRAY8" version does have some (bayer?) artifacts:
![image](https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/assets/24491422/ba1be144-f56a-4a91-b814-bb585f32a14b)

**Comment by TIS-Stefan** [comment]
Hello 
Sorry for being missleading, the format should stay at "BGRx", then the tcambin performs the debayering from rggb to BGRx automatically. BGRx is the output format you may want from tcambin. 

From the tcam-ctrl output we see, that the camera has no 640x480 resolution in its USB descriptor. Therefore, v4l2 refused to use the 640x480 resolution and you got the "not negotiated -4" error. You did correctly changing the resolution. 

Stefan

**Comment by bartonp2** [comment]
Ah I see. Thanks for the help! This worked :)
