### ISSUE TITLE
`FmtDesc`class methods in python-common/TIS.py are outdated

### ISSUE THREAD

**Issue by Julian-Hochhaus** [TheImagingSource/Linux-tiscamera-Programming-Samples#40]
Hey guys,
Thanks for the great work. While playing around with a TIS camera and python, I found that the class methods of `FmtDesc` in `python-common/TIS.py` are outdated.

The class is given by:

[FmtDesc](https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/aa19ff49ae0e01182e537a08445a027f450469d7/python/python-common/TIS.py#L427C1-L469C78)

```
class FmtDesc:
""""""

    def __init__(self,
                 name: str = "",
                 fmt: str = ""):
        self.name = name
        self.fmt = fmt
        self.res_list = []

    def get_name(self):
        if self.name == "image/jpeg":
            return "jpeg"
        else:
            return self.fmt

    def get_resolution_list(self):

        res_list = []

        for entry in self.res_list:
            res_list.append(entry.resolution)

        return res_list

    def get_fps_list(self, resolution: str):

        for entry in self.res_list:
            if entry.resolution == resolution:
                return entry.fps

    def generate_caps_string(self, resolution: str, fps: str):
        if self.name == "image/jpeg":
            return "{},width={},height={},framerate={}".format(self.name,
                                                               resolution.split('x')[0],
                                                               resolution.split('x')[1],
                                                               fps)
        else:
            return "{},format={},width={},height={},framerate={}".format(self.name,
                                                                         self.fmt,
                                                                         resolution.split('x')[0],
                                                                         resolution.split('x')[1],
                                                                         fps)
```

The class methods `get_resolution_list` and `get_fps_list` are both trying to get the `resolution` property of entries in `self.res_list`.
However, the `self.res_list` contains instances of the following class:
[ResDesc](https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/blob/aa19ff49ae0e01182e537a08445a027f450469d7/python/python-common/TIS.py#L416):

```
class ResDesc:
    """"""
    def __init__(self,
                 width: int,
                 height: int,
                 fps: list):
        self.width = width
        self.height = height
        self.fps = fps
```
These instances therefore do not hold the property `resolution`. 
I assume, the resolution entry should be strings in the format "`width`x`height`". 

Modifying the `class ResDesc` to:

```
class ResDesc:
    """"""
    def __init__(self,
                 width: int,
                 height: int,
                 fps: list):
        self.width = width
        self.height = height
        self.fps = fps
        self.resolution=f"{width}x{height}"
```
seems to work just fine.

Kind regards,
Julian

**Comment by Julian-Hochhaus** [comment]
Furthermore, I noticed the presence of a potentially updated second version of `TIS.py` in the `capture-sequence` directory—likely the most recent iteration, last modified just last month. I've made modifications to the `ResDesc` class in both `TIS.py` files, as explained above. 
Please review the changes at your convenience and consider accepting my pull request if they align with your preferences.

**Comment by TIS-Stefan** [comment]
Hello Julian

Yes, there are different versions of TIS.py. I fulfilled your merge request. Thank you very much!

Stefan

**Comment by Julian-Hochhaus** [comment]
You are welcome!
