### ISSUE TITLE
Update readmes/examples for the refactored TIS.py

### ISSUE THREAD

**Issue by slabua** [TheImagingSource/Linux-tiscamera-Programming-Samples#42]
All the README files and examples need to be updated to work with the newly refactored TIS.py module, since basically all the method names have changed to lowercase, and perhaps there are also other modifications.

**Comment by TIS-Stefan** [comment]
Hello
You are right. Howeever, when IC Imaging Control 4 for Linux will be released, these samples will become obsolete.

Stefan

**Comment by slabua** [comment]
Hi Stefan, thank you
Is IC Imaging Control the equivalent replacement for the TIS.py module?
I just got this camera so I still don't know about it well.

**Comment by TIS-Stefan** [comment]
Hi
IC 4 is a complete SDK. Access to cameras etc is done by GenTL. The source code using IC 4 will be the same in Windows and Linux. The documentation can be found at https://www.theimagingsource.com/en-us/documentation/ic4python/index.html

Stefan

**Comment by slabua** [comment]
Thank you!
