### ISSUE TITLE
Is there a C++ ROS Programming Sample?

### ISSUE THREAD

**Issue by xXBasti** [TheImagingSource/Linux-tiscamera-Programming-Samples#5]
Hi,

Could you please provide a ROS C++ sample which uses your library.
Unfortunately, the python sample does only use a roslaunch command which provides bad quality with a high latency and does not uses much of your library.

**Comment by TIS-Stefan** [comment]
Currently there is no ROS C++ example, but with the availalbe ROS v4l2 / gstreamer plugins this should work.
