### ISSUE TITLE
"wait_for_image" is not defined.

### ISSUE THREAD

**Issue by Kaiqgs** [TheImagingSource/Linux-tiscamera-Programming-Samples#6]
On the "TIS.py" file, inside the "Save an image on trigger in Python" folder, the method "Snap_image" line 140, calls "wait_for_image" but that is not defined, and it probably should be replaced by "self.wait_for_image(timeout)"

**Comment by TIS-Stefan** [comment]
Should be fixed in line 120 of tis.py
