### ISSUE TITLE
software trigger mode don't work with the appsink to copy data from camera

### ISSUE THREAD

**Issue by wutongyu98** [TheImagingSource/Linux-tiscamera-Programming-Samples#7]
Hi, I am a computer vision engineering and using two usb3.1 board cameras (DMM 37UX273-ML) from imaging source for stereo vision. 

I am wondering, if you can help to provide a C or C++ sample code can control the exposure time, trigger the camera using software trigger mode, and most importantly copy the data out from camera.

I need to control the exposure time and synchronize action of two cameras. All these parameter can be controlled separately, but when put them together, they don't work. I provide my test detail in the following: 
First, I am using the library (https://github.com/TheImagingSource/tiscamera).  I can successfully run the "06-softwaretrigger" and "07-appsink" from the "tiscamera" example . I know "07-appsink" is used to access data via "sink" from camera, and "06-softwaretrigger" is used to trigger the camera action. But when put them together, I cannot get the data out. Could you provide a short example how to get these two function (software trigger and copy data from camera) work together? 

Second, I also test the C++ library (https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples), and modified the example(Linux-tiscamera-Programming-Samples), but I can not synchronize the action of the two cameras. 

Thanks,

**Comment by TIS-Stefan** [comment]
Sorry for coming back to you so late, but our notifying system started to fail totally.
The https://github.com/TheImagingSource/tiscamera/blob/master/examples/c/02-set-properties.c sample shows, how to set properties. If you want to set exposure time, then you must disable gain and exposure automatics first.
There is also a sample at https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples/tree/master/Using%20Properties%20in%20C%2B%2B

> Second, I also test the C++ library (https://github.com/TheImagingSource/Linux-tiscamera-Programming-Samples), and modified the example(Linux-tiscamera-Programming-Samples), but I can not synchronize the action of the two cameras.

So, what are you doing in your code?

Stefan
